#!/usr/bin/env python3
"""
Audit an exported SAC theme and emit a starter spec.

  inspect_theme.py theme.json                     # report only
  inspect_theme.py theme.json --emit-spec spec.json

Always run this first. The export is generated by whatever tooling the customer
used against whatever SAC version they are on, so never assume the swatch set,
the roles, or the section layout match the last one you saw. The report tells
you what you actually have; the emitted spec is keyed to THIS file's swatch ids
and role descriptions, so editing it cannot drift from reality.
"""
import argparse
import collections
import json
import re
import sys

FAM_KEYS = ("fontname", "fontFamily", "family")
TYPO = {"fontsize", "fontSize", "fontWeight", "bold", "regular", "fontStyle"}
FONT_ATTRS = {"fontsize", "fontSize", "bold", "italic", "underline", "strikethrough",
              "forecolor", "color", "fontWeight", "fontStyle", "black", "regular",
              "commentstyle", "defaultFont", "fontColorSwatchId", "includeUndo",
              "title", "subtitle", "footer"}


def swatch_block(doc):
    return doc["theme"]["colors"]["preferences"][0]["settings"]


def walk(o, path=""):
    if isinstance(o, dict):
        yield path, o
        for k, v in o.items():
            yield from walk(v, f"{path}/{k}")
    elif isinstance(o, list):
        for i, v in enumerate(o):
            yield from walk(v, f"{path}[{i}]")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("theme")
    ap.add_argument("--emit-spec")
    a = ap.parse_args()

    doc = json.load(open(a.theme))

    print("=" * 70)
    print(f"format {doc.get('format')!r}  schemaVersion {doc.get('schemaVersion')}")
    print(f"top-level sections: {list(doc.keys())}")
    src = doc.get("source", {})
    if src:
        print(f"exported from SAC ui5 {src.get('ui5Version')} mode {src.get('mode')!r}")

    # ---------------------------------------------------------- swatches
    st = swatch_block(doc)
    vals = st["swatches"]["values"]
    assigned = [s for s in vals if not s.get("isUnassigned")]
    by_type = collections.Counter(s["swatchType"] for s in vals)
    print(f"\nswatches: {len(vals)} slots, {len(assigned)} assigned")
    for k, v in by_type.items():
        n = sum(1 for s in vals if s["swatchType"] == k and not s.get("isUnassigned"))
        print(f"   {k:<20} {n} assigned of {v}")

    # This mirror is the single most-missed thing in the file. If you update the
    # live swatches and not this block, SAC's "reset to theme default" reverts
    # the story to SAP stock colours.
    mirror = "defaultColorSettings" in st
    print(f"\ndefaultColorSettings mirror present: {mirror}")
    if mirror:
        mv = st["defaultColorSettings"]["swatches"]["values"]
        same = sum(1 for x, y in zip(vals, mv) if x.get("baseColor") == y.get("baseColor"))
        print(f"   mirrors the live table exactly: {same == len(vals)} ({same}/{len(vals)})")
        print("   -> any swatch edit must be applied to BOTH blocks")

    print("\nassigned swatch roles:")
    for s in assigned:
        print(f"   {s['id']:<22} {s['baseColor']:<13} {s.get('description', '')}")

    # ---------------------------------------------------------- palettes
    pal = doc["theme"]["palettes"]["preferences"][0]["settings"]["palettes"]
    print(f"\npalette groups: {list(pal.keys())}")
    drift = 0
    m = {s["id"]: s["baseColor"] for s in vals}
    for g in ("standard", "waterfall_standard"):
        for e in pal.get(g, []):
            resolved = [m.get(i) for i in e["swatchIds"]]
            bad = [(i, c, r) for i, c, r in zip(e["swatchIds"], e["colors"], resolved) if c != r]
            drift += len(bad)
            print(f"   {g:<20} {e.get('mappingPaletteId'):<42} {len(e['colors'])} colours"
                  + (f"  <-- {len(bad)} out of sync" if bad else ""))
    for g in ("gradient", "diverging", "sequential", "variance", "single_color"):
        if g in pal:
            n = len(pal[g]) if isinstance(pal[g], list) else 1
            print(f"   {g:<20} {n} entr{'y' if n == 1 else 'ies'}")
    if drift:
        print(f"   NOTE {drift} palette colour(s) disagree with their own swatchIds in the")
        print("        source. Rebuilding colours from swatchIds fixes this.")

    # ------------------------------------------- cached literals elsewhere
    other = {k: doc[k] for k in doc if k not in ("theme", "format", "schemaVersion",
                                                 "exportedAt", "source")}
    blob = json.dumps(other)
    lits = collections.Counter(re.findall(r'"(#[0-9A-Fa-f]{3,8})"', blob))
    refs = collections.Counter(re.findall(r'"(\w*[Ss]watch[Ii]d)"\s*:', blob))
    print(f"\noutside theme.colors / theme.palettes ({', '.join(other)}):")
    print(f"   {sum(refs.values())} swatch references")
    print(f"   {sum(lits.values())} cached literal colours sitting beside them")
    print("   -> these are resolved copies, not bindings. If your import writes these")
    print("      sections back verbatim, stale literals can win over the swatch.")

    # ------------------------------------------------------- font coverage
    set_, empty, missing = 0, 0, 0
    for _, node in walk(other):
        fam = [k for k in FAM_KEYS if k in node]
        if fam:
            if all(not str(node[k]).strip() for k in fam):
                empty += 1
            else:
                set_ += 1
        elif set(node) <= FONT_ATTRS and set(node) & TYPO:
            missing += 1
    fams = collections.Counter()
    for _, node in walk(other):
        for k in FAM_KEYS:
            if isinstance(node.get(k), str) and node[k].strip():
                fams[(k, node[k])] += 1
    print(f"\nfont families: {set_} set, {empty} present but empty, {missing} absent entirely")
    for (k, v), n in fams.most_common(10):
        print(f"   {n:>3}  {k:<11} {v!r}")
    if empty or missing:
        print("   -> empty and absent slots fall back to the SAC default at render time,")
        print("      which defeats a brand font. build_theme.py fills them.")

    # ---------------------------------------------------------- emit spec
    if a.emit_spec:
        spec = {
            "brand": "TODO customer name",
            "notes": "Replace every color below. Roles come from this export.",
            "font": {"family": "", "fallback": "Arial, Helvetica, sans-serif",
                     "apply": False},
            "activate": {},
            "headerBar": {},
            "swatches": {s["id"]: {"role": s.get("description", ""),
                                   "color": s["baseColor"]} for s in assigned},
            "palettes": {
                "variance": pal["variance"][0]["colors"] if pal.get("variance") else [],
                "single_color": [e["color"] for e in pal.get("single_color", [])],
            },
        }
        spare = collections.defaultdict(list)
        for s in vals:
            if s.get("isUnassigned"):
                spare[s["swatchType"]].append(s["id"])
        spec["_spareSlots"] = {k: v[:3] for k, v in spare.items()}
        json.dump(spec, open(a.emit_spec, "w"), indent=2)
        print(f"\nwrote starter spec -> {a.emit_spec}")
        print("   every swatch currently holds its SAP stock colour; edit the")
        print("   'color' values, then run build_theme.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
